[build]
    functions="functions"

[[redirects]]
    to="/.netlify/functions/server/api/:splat"
    from="/*"
    status=200

[[redirects]]
    to="/dist/index.html"
    from="/"
    status=200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"